input_dir: C:/Users/username/path/to/input/folder
output_dir: C:/Users/username/path/to/output/folder
default_image_format: jpg
default_video_format: mp4
log_level: INFO

# Supported Formats
supported_image_formats:
  - jpg
  - jpeg
  - png
  - bmp
  - webp
  - raw

supported_video_formats:
  - mp4
  - avi
  - mkv
  - mov
  - webm